name: Test Action

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


jobs:
  remote:
    runs-on: ubuntu-latest
    
    steps:
      #- name: Checkout code
    
        #run: |
          #echo ${{secrets.SSHKey}}
          #echo madhav
          
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup remote
        run: |
          echo "${{secrets.SSHKey}}" | sudo tee /etc/ssh/authorized_keys
          sudo tee /etc/ssh/sshd_config <<EOF
            PasswordAuthentication no
            PubkeyAuthentication yes
            AuthorizedKeysFile /etc/ssh/authorized_keys
            PermitRootLogin no
            Subsystem sftp /usr/lib/openssh/sftp-server
          EOF
          sudo systemctl restart sshd
          echo 'SSH_KNOWN_HOSTS<<EOF' >> $GITHUB_ENV
          echo $(ssh-keyscan 13.232.12.245) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        
          echo " ${{env.SSH_KNOWN_HOSTS}}"
      - name: With everything
        # uses: tomasnorre/ansible-cli-action@0.0.5
        # with:
        # command: "ansible-playbook ./playbook/playbook1.yaml"
        uses: dawidd6/action-ansible-playbook@v2

        with:
          playbook: playbook.yaml
          key: ${{secrets.SSHKey}}
          known_hosts: ${{env.SSH_KNOWN_HOSTS}}
          directory: playbook
          sudo: true
          #vault_password: ${{secrets.SSHKey}}
          inventory: |
            [ansible_client]
            13.232.12.245
