name: Test Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  remote:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
    
        run: |
          echo ${{secrets.SSHKey}}
          echo madhav
